/**
 * Sandboxed AI prototype preview for Development agent.
 * Uses srcDoc + restrictive sandbox — never runs in the main ESC window.
 * HTML is only from agent-generated content or a safe layout built from agent text fields.
 */
import { useMemo, useState } from 'react';
import { asRecord, isNonEmpty, str } from './shared';

type Viewport = 'desktop' | 'tablet' | 'mobile';

function escapeHtml(s: string) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Build a minimal marketing site shell only from agent-provided strings (no invented stats). */
export function buildPrototypeFromFields(data: unknown): string {
  const r = asRecord(data);
  const title = escapeHtml(
    str(r.productName || r.projectName || r.title || 'Your product').slice(0, 80),
  );
  const hero = escapeHtml(
    str(r.productRequirements || r.executiveSummary || r.valueProposition || 'A product experience generated from your ESC plan.').slice(0, 400),
  );
  const features = Array.isArray(r.mvpFeatures)
    ? r.mvpFeatures.map(f => (typeof f === 'string' ? f : JSON.stringify(f))).slice(0, 6)
    : [];
  const stack = r.recommendedStack
    ? (typeof r.recommendedStack === 'string'
        ? [r.recommendedStack]
        : Array.isArray(r.recommendedStack)
          ? r.recommendedStack.map(String)
          : Object.entries(r.recommendedStack as object).map(([k, v]) => `${k}: ${v}`))
    : [];

  const featureHtml = features.length
    ? features.map(f => `<div class="card"><h3>${escapeHtml(String(f).slice(0, 80))}</h3><p>${escapeHtml(String(f).slice(0, 180))}</p></div>`).join('')
    : '<div class="card"><h3>MVP feature</h3><p>Add MVP features in the development plan to populate this section.</p></div>';

  const stackHtml = stack.length
    ? `<ul class="stack">${stack.slice(0, 8).map(s => `<li>${escapeHtml(String(s).slice(0, 100))}</li>`).join('')}</ul>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${title} · ESC Prototype</title>
<style>
  :root { --bg:#F0F9FF; --ink:#0F172A; --muted:#64748B; --primary:#0EA5E9; --primary-deep:#0284C7; --card:#fff; }
  * { box-sizing:border-box; }
  body { margin:0; font-family:Inter,system-ui,sans-serif; color:var(--ink); background:var(--bg); }
  nav { display:flex; justify-content:space-between; align-items:center; padding:1rem 1.25rem; background:#fff; border-bottom:1px solid #e2e8f0; position:sticky; top:0; }
  .brand { font-weight:800; letter-spacing:.04em; color:var(--primary-deep); }
  .nav-links { display:flex; gap:1rem; font-size:.85rem; color:var(--muted); }
  .btn { background:linear-gradient(135deg,#0EA5E9,#0284C7); color:#fff; border:0; border-radius:999px; padding:.65rem 1.1rem; font-weight:700; cursor:pointer; }
  .btn.ghost { background:#fff; color:var(--primary-deep); border:1px solid #bae6fd; }
  hero, .hero { display:block; padding:3rem 1.25rem 2.5rem; max-width:960px; margin:0 auto; }
  h1 { font-size:clamp(1.8rem,4vw,2.6rem); line-height:1.1; letter-spacing:-.03em; margin:0 0 1rem; }
  .lead { color:var(--muted); font-size:1.05rem; line-height:1.7; max-width:36rem; }
  .actions { display:flex; flex-wrap:wrap; gap:.6rem; margin-top:1.4rem; }
  .section { max-width:960px; margin:0 auto; padding:1.5rem 1.25rem 2.5rem; }
  .section h2 { font-size:1.15rem; margin:0 0 1rem; }
  .grid { display:grid; gap:1rem; grid-template-columns:repeat(auto-fill,minmax(200px,1fr)); }
  .card { background:var(--card); border:1px solid #e2e8f0; border-radius:1rem; padding:1rem; box-shadow:0 8px 24px rgba(15,23,42,.04); }
  .card h3 { margin:0 0 .4rem; font-size:.95rem; }
  .card p { margin:0; color:var(--muted); font-size:.85rem; line-height:1.5; }
  .stack { margin:0; padding-left:1.1rem; color:var(--muted); font-size:.9rem; }
  footer { margin-top:2rem; padding:1.5rem 1.25rem; border-top:1px solid #e2e8f0; background:#fff; text-align:center; color:var(--muted); font-size:.8rem; }
  @media (max-width:640px){ .nav-links{display:none;} }
</style>
</head>
<body>
  <nav>
    <div class="brand">${title}</div>
    <div class="nav-links"><span>Product</span><span>Features</span><span>Stack</span></div>
    <button class="btn" type="button">Get Started</button>
  </nav>
  <section class="hero">
    <h1>${title}</h1>
    <p class="lead">${hero}</p>
    <div class="actions">
      <button class="btn" type="button">Primary action</button>
      <button class="btn ghost" type="button">Learn more</button>
    </div>
  </section>
  <section class="section">
    <h2>Core features</h2>
    <div class="grid">${featureHtml}</div>
  </section>
  ${stackHtml ? `<section class="section"><h2>Recommended stack</h2>${stackHtml}</section>` : ''}
  <footer>Prototype generated by ESC from your development plan · Not a production app</footer>
  <script>
    document.querySelectorAll('button').forEach(function(b){
      b.addEventListener('click', function(e){ e.preventDefault(); b.textContent = b.textContent === 'Clicked ✓' ? b.dataset.label || 'Action' : (b.dataset.label=b.textContent,'Clicked ✓'); });
    });
  </script>
</body>
</html>`;
}

function extractAgentHtml(data: unknown): string | null {
  const r = asRecord(data);
  for (const k of ['landingPageHtml', 'html', 'generatedHtml', 'prototypeHtml']) {
    const v = r[k];
    if (typeof v === 'string' && v.trim().length > 40 && /<html|<body|<div|<section/i.test(v)) {
      return /<!doctype|<html/i.test(v)
        ? v
        : `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ESC Prototype</title></head><body>${v}</body></html>`;
    }
  }
  return null;
}

export default function PrototypePreview({ data }: { data: unknown }) {
  const agentHtml = extractAgentHtml(data);
  const [useAgentHtml, setUseAgentHtml] = useState(Boolean(agentHtml));
  const [viewport, setViewport] = useState<Viewport>('desktop');
  const [key, setKey] = useState(0);

  const srcDoc = useMemo(() => {
    if (useAgentHtml && agentHtml) return agentHtml;
    return buildPrototypeFromFields(data);
  }, [useAgentHtml, agentHtml, data]);

  const widths: Record<Viewport, string> = {
    desktop: '100%',
    tablet: '768px',
    mobile: '390px',
  };

  const canDownload = Boolean(srcDoc);

  const downloadHtml = () => {
    if (!srcDoc) return;
    const blob = new Blob([srcDoc], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ESC_Prototype.html';
    a.click();
    URL.revokeObjectURL(url);
  };

  const openPreview = () => {
    const blob = new Blob([srcDoc], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank', 'noopener,noreferrer');
    // revoke after a delay so the new tab can load
    window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
  };

  const hasStructured = isNonEmpty(asRecord(data).mvpFeatures)
    || isNonEmpty(asRecord(data).productRequirements)
    || isNonEmpty(asRecord(data).executiveSummary);

  if (!agentHtml && !hasStructured) {
    return (
      <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
        A visual prototype needs either generated HTML or structured product/MVP fields from the Development agent.
        Switch to the Build roadmap tab for the step-by-step plan, or regenerate with a product/website prompt.
      </div>
    );
  }

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex flex-wrap gap-1 rounded-xl border border-slate-200 bg-white p-1">
          {(['desktop', 'tablet', 'mobile'] as Viewport[]).map(v => (
            <button
              key={v}
              type="button"
              onClick={() => setViewport(v)}
              className={`rounded-lg px-3 py-1.5 text-xs font-semibold capitalize ${
                viewport === v ? 'bg-primary-600 text-white' : 'text-slate-600 hover:bg-slate-50'
              }`}
            >
              {v}
            </button>
          ))}
        </div>
        <div className="flex flex-wrap gap-2">
          {agentHtml && (
            <button
              type="button"
              onClick={() => setUseAgentHtml(v => !v)}
              className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700"
            >
              {useAgentHtml ? 'Show layout prototype' : 'Show agent HTML'}
            </button>
          )}
          <button type="button" onClick={() => setKey(k => k + 1)} className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700">Refresh</button>
          <button type="button" onClick={openPreview} className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700">Open preview</button>
          {canDownload && (
            <button type="button" onClick={downloadHtml} className="rounded-lg bg-primary-600 px-3 py-1.5 text-xs font-semibold text-white">Download HTML</button>
          )}
        </div>
      </div>

      <p className="m-0 text-[11px] text-slate-500">
        Sandboxed preview (isolated from ESC). {agentHtml && useAgentHtml ? 'Using agent-generated HTML.' : 'Layout built only from your development-plan fields — not invented market data.'}
      </p>

      <div className="overflow-auto rounded-2xl border border-slate-200 bg-slate-100 p-3" style={{ maxHeight: 520 }}>
        <div className="mx-auto overflow-hidden rounded-xl border border-slate-200 bg-white shadow-md transition-all" style={{ width: widths[viewport], maxWidth: '100%', height: 460 }}>
          <iframe
            key={key}
            title="ESC prototype preview"
            srcDoc={srcDoc}
            sandbox="allow-scripts"
            className="h-full w-full border-0 bg-white"
            referrerPolicy="no-referrer"
          />
        </div>
      </div>
    </div>
  );
}
